auth:
    email-password: ""
    email-smtp-host: ""
    email-smtp-port: "3306"
    email-username: root
    enable-email: false
    enable-oauth2: false
    enable-public-registration: false
    enable-qq: false
    enable-telegram: false
    qq-app-id: ""
    qq-app-key: ""
    telegram-bot-token: ""
captcha:
    enabled: true
    expire-time: 300
    height: 40
    length: 4
    width: 120
cdn:
    base-endpoint: https://cdn.spiritlhl.net/
    endpoints:
        - https://cdn0.spiritlhl.top/
        - http://cdn3.spiritlhl.net/
        - http://cdn1.spiritlhl.net/
        - http://cdn2.spiritlhl.net/
cors:
    mode: ""
    whitelist: []
invite-code:
    enabled: false
    required: false
jwt:
    buffer-time: 1d
    expires-time: 7d
    issuer: oneclickvirt
    signing-key: ""
mysql:
    auto-create: true
    config: charset=utf8mb4&parseTime=True&loc=Local
    db-name: oneclickvirt
    engine: InnoDB
    log-mode: error
    log-zap: false
    max-idle-conns: 20
    max-lifetime: 1800
    max-open-conns: 200
    password: ""
    path:
    port:
    prefix: ""
    singular: false
    username: root
quota:
    default-level: 1
    instance-type-permissions:
        min-level-for-container: 1
        min-level-for-delete-container: 2
        min-level-for-delete-vm: 3
        min-level-for-reset-container: 1
        min-level-for-reset-vm: 3
        min-level-for-vm: 3
    level-limits:
        1:
            max-instances: 1
            max-resources:
                bandwidth: 100
                cpu: 1
                disk: 1025
                memory: 350
            max-traffic: 102400
        2:
            max-instances: 3
            max-resources:
                bandwidth: 200
                cpu: 2
                disk: 20480
                memory: 1024
            max-traffic: 204800
        3:
            max-instances: 5
            max-resources:
                bandwidth: 500
                cpu: 4
                disk: 40960
                memory: 2048
            max-traffic: 307200
        4:
            max-instances: 10
            max-resources:
                bandwidth: 1000
                cpu: 8
                disk: 81920
                memory: 4096
            max-traffic: 409600
        5:
            max-instances: 20
            max-resources:
                bandwidth: 2000
                cpu: 16
                disk: 163840
                memory: 8192
            max-traffic: 512000
redis:
    addr: ""
    db: 0
    password: ""
sysm:
    db-type: mysql
system:
    addr: 8888
    db-type: mysql
    env: production
    iplimit-count: 15000
    iplimit-time: 3600
    oss-type: local
    use-multipoint: false
    use-redis: false
    frontend-url: ""
    provider-inactive-hours: 72
    oauth2-state-token-minutes: 15
task:
    delete-retry-count: 3
    delete-retry-delay: 2
zap:
    compress-logs: true
    director: storage/logs
    encode-level: LowercaseLevelEncoder
    format: console
    level: info
    log-in-console: false
    max-array-elements: 5
    max-backups: 15
    max-file-size: 5
    max-log-length: 2000
    max-string-length: 1000
    prefix: '[oneclickvirt]'
    retention-day: 3
    show-line: false
    stacktrace-key: stacktrace
